### ISSUE TITLE
Quasar Graphql wrapper questions

### ISSUE THREAD

**Issue by 3kynox** [quasarframework/quasar-wrapper-graphql-api#2]
Hello there !

I have few questions about the new wrappers for server part as I'm currently trying to implement this for a project.

- quasar wrap graphql-api do not work yet on current quasar-cli, when I'm using it, it returns quasar wrap help details showing only cordova / electron wrappers, do I have missed to do something ?

- What's going on behind the scene ? Is there a server folder created ?
- Related question, can we build separately server / client with webpack ?
- What is Apollo and why using it ?
- I started to learn about Graphql and it looks like just a query synthax to generate formatted json data at the end. Finally my question is : Can we use Graphql with FeatherJS (that normally support now Graphql) ? It makes more sense to me to have FeatherJS to manage API communication with Graphql for the json language synthax.

Thanks !

**Comment by claustres** [comment]
Hello and thanks for your interest. I am not responsible of the GraphQL wrapper but can answer some general questions and some about Feathers. 

First the wrappers are not yet part of the CLI and meanwhile it should be used as detailed [here](https://github.com/quasarframework/quasar-wrapper-feathersjs-api). The wrappers create an `api` folder in the root directory of your quasar template containing the server code.

Building server-side code using webpack does not make sense at all because it does not run in a browser. However, for the Feathers wrapper we use babel so that we can use a similar syntax than in the client (import/export, etc.).

As far as I know Feathers supports GraphQL through the [Waterline adapter](https://github.com/feathersjs/feathers-waterline) and there is a [side project](https://github.com/swarthout/feathers-apollo) for Apollo as well. The wrapper generates a template based on the [NeDB adapter](https://github.com/feathersjs/feathers-nedb/) but you can change it easily.

**Comment by 3kynox** [comment]
Hey, thanks for really fast and detailed answer!

You said : **"Building server-side code using webpack does not make sense"** : 
It make sense as at the end for my project users, server package and client package will certainly have be installed on different places, which is a default requirement usually. 
Server package installed on a server, and client from the user end computer, as a native app or something else. Then both server/client communicating.

About featherjs, according of what you said and given links, it should be possible to have both featherjs / graphql with apollo using one of them. I'll have to find how exactly now :)

But definitely a cool thing, maybe with SSR enabled later from the quasar-featherjs repo on my pwa template quasar app.

**Comment by claustres** [comment]
Don't forget that a lot of Node.js packages rely on compiled native libraries, notably DB adapters like Mongo, etc. So you won't do anything with that using webpack... For server-side autonomous packaging I strongly recommend using a container technology like Kubernetes or Docker. For client-side at the end the app built by Webpack is simply the `dist` directory you can move anywhere you'd like easily.

Anyway you can easily adapt the wrappers as well so that you can have two separated folders for client/server, you will simply have to tweak the config a little bit.

**Comment by 3kynox** [comment]
Ok thanks for clarification. I was thinking about webpack building "server side only" package because of this project : https://github.com/icebob/vue-express-mongo-boilerplate/blob/master/build/webpack.server.config.js where the guy here use `npm run build:server` to generate server part.

Anyway, While I'm building the server part, I'm ok to PR on a separate branch featherjs / graphql integration. I planned to PR also later about quasar unit tests with PhantomJS: Karma + Mocha + karma-webpack and end to end tests using Nightwatch for example. As tests is no longer on quasar currently.

**Comment by claustres** [comment]
It could work as long as you are not using native libraries/executables but not so generic IMHO.

Tests would be a really great thing, I don't have much time now but plan to look into as well, the best thing I've found so far seems to be http://codecept.io/.

**Comment by 3kynox** [comment]
Really cool discussion, Quasar is awesome ! I'm closing here and let you know on further work on this task & contributions later on.
